version: "3"

networks:
  pubel:

volumes:
  prometheus_data:
  grafana_data:

services:
  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - pubel

  prometheus:
    image: prom/prometheus:v2.37.9
    restart: unless-stopped
    volumes:
      - ./docs/examples/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=1d'
    ports:
      - "9090:9090"
    networks:
      - pubel

  loki:
    image: grafana/loki:2.8.3
    ports:
      - "3100:3100"
    volumes:
      - ./docs/examples/config/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - pubel

  promtail:
    image: grafana/promtail:2.8.3
    ports:
      - "8500:8500/udp"
      - "9080:9080"
    volumes:
      - ./docs/examples/config/promtail.yaml:/etc/promtail/config.yml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - pubel

  buddy-exporter:
    image: pubeldev/buddy-prometheus-exporter:v0.2.4
    environment:
      - BUDDY_EXPORTER_PORT=10009
      - BUDDY_EXPORTER_SCRAPE_TIMEOUT=1
      #- BUDDY_EXPORTER_CONFIG=/etc/buddy-prometheus-exporter/buddy.yaml
    volumes:
      - type: bind
        source: ./docs/examples/config/buddy.yaml
        target: /app/buddy.yaml
    ports:
      - "10009:10009"
    networks:
      - pubel

  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    user: "0"
    volumes:
      - ./docs/examples/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-xyzchart-panel ## TODO
    networks:
      - pubel

