apiVersion: 1
datasources:
  - name: LokiE
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090