server:
  log_level: info

metrics:
  global:
    scrape_interval: 30s
    remote_write:
    - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
      basic_auth:
        username: username
        password: pass
  configs:
    - name: agent
      scrape_configs:
      - job_name: "buddy-exporter"
        static_configs:
          - targets: ["buddy-exporter:10009"]
      - job_name: "promtail"
        static_configs:
          - targets: ["promtail:9080"]
      - job_name: "node-exporter"
        static_configs:
          - targets: ["node-exporter:9100"]