server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

#- job_name: syslog
#  syslog:
#    listen_address: localhost:8500
#    idle_timeout: 120
#    label_structured_data: true
#    use_incoming_timestamp: true
#    labels:
#      job: "syslog"

- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: systemlogs
      __path__: /var/log/*.log